# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
  pull_request:

jobs:

  # BUILD PROJECT
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - run: npm ci
      - run: npm run build

  # RUN TEST
  test:
    runs-on: ubuntu-latest

    needs: [ build ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install codecov dependency
        run: npm install -g codecov

      - run: npm ci
      - run: npm run test:cov
      - run: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # PUBLISH DOCUMENTATION
  publish-docs:

    # condition to run this job
    needs: [ test ]
    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest
    steps:
      # checkout code and setup node
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x

      # pipeline actions
      - run: npm ci
      - run: npm run docs

      # deploy to gh-pages
      - name: "Deploy page"
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

  # PUBLISH PACKAGE
  publish-npm:
    needs: [ test ]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
