# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
  pull_request:

jobs:

# BUILD PROJECT
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Cache project node-modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            lib
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build

# RUN TEST
  test:
    runs-on: ubuntu-latest

    needs: [build]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Cache project node-modules
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install codecov dependency
        run: npm install -g codecov

      - run: npm run test:cov
      - run: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

# PUBLISH PACKAGE
#  test:
#    runs-on: ubuntu-latest
#
#    needs: [build]
#
#    strategy:
#      matrix:
#        node-version: [14.x]
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Cache project node-modules
#        uses: actions/cache@v2
#        with:
#          path: |
#            node_modules
#            lib
#          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
#
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v2
#        with:
#          node-version: ${{ matrix.node-version }}
#
#      - name: Install codecov dependency
#        run: npm install -g codecov
#
#      - run: npm run test:cov
#      - run: codecov
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
